language: python
python:
- 3.5
env:
- pipenv
install:
- pipenv install
script:
- py.test --cov=tests
branches:
  only:
  - sivubranch
  - master
deploy:
  provider: heroku
  api_key:
    secure: PAnwQlbOzqriAFd5Zn46oZAZI/m4XtZ1fU0HjmyCcVa9wcUuAy5mSw0dpH2VDsyV17i+wQAJo44+k0yjjcViUAjZzRwaUchXa+NlGLH5Buh7SoTAD8zxl9oyRJ1JpHzIw0AEN6eiF2BqaIg4oqJXi9hlJaDybcLkOLR8y63gUGE8X8WUZ+6qPNzq/4nuAo8csy+R5NhAPre+uzoMAIA/wNSbHO8wZhaTTnDD5l1yBCyNYOae2TtrnTEP5dmHX/daDamlS0/v4BH2PqIv20Zq36cL6Eo5sDubWt16fQMPY/K27cyW9KcjdKkMZvMrZ8GHqB6ueXVkI/aOmSmUcCLtldu17h/OwY7FhlcrI4KZW4SJg96pdHZGQpaQl9Pg1H+f5ySiBij5T2YH8NBHlKl5nkuKYksPgOMMEaNwG0rFSGca5CLkwKG6qGv6+puvCZ2VXhTnR1Tn6bBkvuum3WRS/aZOToVQ3en4bMOsHXTmWYhOj0h0jHEFsEKESwzszbkpfWEb38VpmFRCHafMvY5X7b++6uQWODCk4bQtpIswqzuJ7xQtq6hjd2t/cxiRwEizIK6pCOkT6dZKTOSefiwnuInZoV8JDSPYOmIczU3/L+7TaJSNAy4htAbH7t/9lOSd14pjl/xMN81HbczJgFfSeK97U0HuNfycNdaX39Yn8dQ=
  app: flaskappteam
  on:
    repo: sivu-t/flaskappteam
    branch: sivubranch
