language: python
python:
- 3.5
env:
- pipenv
install:
- pipenv install
script:
- py.test --cov=tests
branches:
  only:
  - sivubranch
  - master
deploy:
  provider: heroku
  api_key:
    secure: QaebM3iqvvVWrcp88XCjD73QC3fpAu+H1acxRvOA70DdqzyyfiYhSGzoOjYxLOOBy02SFJBik7TY2M6tJBQjJUPRTCYft9UulRqTps7PNRt2kNV70i80McuGRMbMCDg0Ety9SJew0kEImvgbvjNrNXRM4xrssqCvksv2X/tynBEb6nbn/BrWEt8giS4rAfrGzH66+6g71hUgFgXWqlRYF1SmsJcXNlGF7uye1gj/1jTDXTz3tdWO8wVBZV/leKpkcbAiC8LVSOVGy8o3IpWOXMNukv1cA+uC7gyQzHh3833pxwrcDxQqq2r1Z21wBgZA1EYYSOOHZ/O6KmNOgi0xPjJpVh5hmSzkA0BdYa27zF6S0Gp4nOF32ZoqrsN4hUMXtx/oZv4phv4v9J18wA/e0sv1UKlNQOm5PNctub3MAl7MtM79d4CUJipparPocEAytxHwc3xpBUehVeD1Fj/Vp7QkPD1FWXhJzJn5RX3NEeovFZarBZcY+BfGAkZbFrNUBQRWvCvvRzWA+R8QRdTWr4IfVT/c4Zl7ykj0zi/Heck5MYf4nFCixvoP2cCTYqJv2VqfRtGTqx6Z/tdBAeCiIc+t2RmD6dgvFpPcKZ3UScn+tS+kN9cdtkoWyN2wTe96Ob5syT7zsQM156iWt/bZd0cMU7pwWxMjkz0L7GUw4sA=
  app: flaskappteam
  on:
    repo: sivu-t/flaskappteam
    branch: sivubranch
