language: python
python:
- 3.5
env:
- pipenv
install:
- pipenv install
script:
- py.test --cov=tests
branches:
  only:
  - sivubranch
  - master
deploy:
  provider: heroku
  api_key:
    secure: bfqRa+Vla0dAHTRInQ6SrNdfav0pyQrXcVgnk+UJB2fiVMqERRMbmxoTGhl+IYZwHyhj0exiGJTosavDNVI/1W0hGI0EfVmsDe4aZP80ay4fxIYvabF6uYzWdAVLpDfc3cLl56xp83r+jITSwijjvz7t0x3kgUZJcgq3YR9xRWDBcIdTcFeUDrVbu5Kdk6un1bcZrUZlBBKtxMtK66Ttj/B969Eb7L5wYFa9rpFOklzQjF9FVzS61JySK1EdBh03AI2qGNouW8G++Oas7Vv87l8dzpOzyNzQrZjQXVBaZYCz0Cp9NLuSI5suHszwOciyMGuOU30NhwZeAUb7D6slLPAh8h0e21zoT0FaI6+Zakn/RG2wg62zZg0N2nzIOUIF35AReUunLhvhSWGTy7E9f6XPJx2VC+CUzrHNXK4WV4b3lPAlvNhHiax1Vajuk5ta1d4hVmJHqJnVWGru2VEyyShSfJPG7t5EKxqBFyDmmEJ930BaRtW4WyiGiCS2+hY14Uo9V3aQkdvWtnpvv9rD4URV4ZMGqPxi7KspqhfPqLRO8Nrw8blio1aWjABuZK9eziWgFc2XYsPkeUfFiWfdb4+SBlmDufqU7aof9ltpMwxsYnfwzoBu1PsaUXcRicZRAfGZI3MdU2r19JkYU+GF7B+1LysvKiwfGpGoN8TtE90=
  app: API request failed.
  on:
    repo: sivu-t/flaskappteam
    branch: sivubranch
