language: python
python:
- 3.5
env:
- pipenv
install:
- pipenv install
script:
- py.test --cov=tests
branches:
  only:
  - sivubranch
  - master
deploy:
  provider: heroku
  api_key:
    secure: i1OUmGaW2NBJhTNQwmYd2Uz74Tw8eRy6jEsWO9fOD8Tv9EK7Zk1x2RoOt2NdFjwUSNQDhskjkYz9t50EXmBKcOEoGS3jCu+mJ8UK10sXDtTu4Gju46lDc0jD1H9bWtlPsfchfSrECtPX+6W3W11RnoJGZM8yDQLYqpnNF1rjeVHBvRRypIgT2jWSddB7Znht97NsE8oyqtysccwVwoei2uG8uZsjU5BX4tc90/6VJghTngUl8QA5x+Ncde7G8sabkCaCUku17KLTF8oxFrtYhUum8i8fawP4LW8WXf5Gz49HTNTxGp2x3j1oasZuwmSkHOS7CXIpHecRmORnpJlxzXDkVXO+Kq+9Wnf+32UaroLsuhWi6OJ6ZpJNQ0jFyW2gJJFJGX1TTXimr1+Qo+JpspjDf8k2NxclxDQuMhH6d4vTppGyBinq2VcAsHk7BDVsayw4HZr03CVrCfMQxos5qGyq020dmW4vWSrAvJqJB9y4ThimT00OOxSfnf3hJqtpAwUN3OETsj3dW+Rm5GlBcfrhKwoIC1BTEPdbZPCiXOfL15/T3cZATrK3lICBPjt+2pxTK5wHEsVlawGzbYbTCyGzpOQnxdzvqSlF4sOHAV8x9FphySWZdV6t8I5JlNSwSgH63Cnh+uqLkBc8KVBYw0Ttvot3CvFC5rjeJ2m+V3s=
  app: flaskappteam
  on:
    repo: sivu-t/flaskappteam
    branch: sivubranch
