language: python
python:
- 3.5
env:
- pipenv
install:
- pipenv install
script:
- py.test --cov=tests
branches:
  only:
  - sivubranch
  - master
deploy:
  provider: heroku
  api_key:
    secure: liWxemXHNxdJ1/ofBIcjfxBxR39o31w6B7jD9E2+l2EuOhHJQQYAQBZ9DgaJrOjhOL5hvNFsucJ4kkqAmRBqfa3/E2YjAcZgm2pHae8E2O/o9TGl4XID6BN8QF2hDPyYXcPHJ8HQTijaCeUNE9h8XsL3y2Y5Y9x2nUO2p0l/C96qpcTdoummY2/H1pVFsy4aZ8yXNt0Whl4oNd0+X80m+db/+2hT2LMXY/+BoXlGgNawWALOCDyhfNyPhabx5+0xFyTTN0rsOiLt4Y1G7REz41lrw98O+ykx2Mn8ZtNyPXtE8B1y6k8Hrty88lA0yDOaDJq0crWy6SOZc01X3WEC3QFyza7L8Q4X0jumDxnWTguEn5RP4C1U3nO34/2ExmIviKjpl1ONq+j0F21+35YYxXddVz7l5Th9l7ENVTZRjrarxS5wtjaWXhXtZ+y91aJ5XwUenQd6D8ZgaPdmg7DqiOMi2l3VX3zonVzDP+ocnGrvHHTGWGtnZxGFnKI8xDN6uaRzUXctjCwjHFqupcdKKhpySLwAEwAVFVykYCrVkaMofMHSR1FBvAisEw00P/QxIy+kk5EpAA9P/bZCFxq8Cp+FLePqAaLKpUuo6A3xL/CGPv5WvIK4bfUiSD7Mqwcq8EGfcLhIfttSXputMj6kN7oFlJnK3Ohsz8mMXFbBmNA=
  app: flaskappteam
  on:
    repo: sivu-t/flaskappteam
    branch: master
