language: python
python:
- 3.5
env:
- pipenv
install:
- pipenv install
script:
- py.test --cov=tests
branches:
  only:
  - sivubranch
  - master
deploy:
  provider: heroku
  api_key:
    secure: L/FUwB5jQIMF4vUfrH7nFMPmWmtp8gr8UW3Ff2hL0V3iRAz5k0ev5XWh5PaSqLYKa54LRJMCiELyZk1XatJ8cQ1Q2wWGWx+eXWXrzTTitPBydQ2wEH2RVOjAqHIONC4hGFRagUjjvqW+lGAG1HxB1GyXgJ9yoYsTIj/T4+yxN6ntqeyoewMWFMg5s91Dl8GUZkuZaHlzfN/ipiFKbmGeeFjtG8BinB6ofk+m4MPSR1f7wZ2hmsgH+Hn7bkbOn4UbsXatdTzixuUb3yt32Lo0o1JT/y/5OUr6QEYmu/g19Pqlu0kHaPNbAwWlxBeXX8zmDo9JNzDlMgb3t9G1og4JqaHA4FoRlXlKcgj0ONmU6GpVCkEUx7k0x+AOg/JzpDYFv6ibt+79NqREvV2d0m0jUbGLpPLa+0AJJEakWZhBgwCv/xbTmP1x7+8PwX3jrl/9gJpEgs4wssFjPu5RTPJrm3Q+t8ReD6p9AE2HfEgI74NNHGrgAJbijiOqgwOCz8wsGc2VW5eYBp2A6L+kLUfbbxmIbqtorA+Yu3fJ5Wx0nJu6azmbWtxRLcONib6glDHZK/iazae4GCqPv0Yv+yUyA7jQ7AiL8fYtr/BdM4jqBzODLyFeYkAlYiLiGDtQp9BWpNXEBtb4GmRG7u0ytRmlUIIUT9AxPLKMcoPTHObve/I=
  app: flaskappteam
  on:
    repo: sivu-t/flaskappteam
    all_branches: true
