language: python
python:
- 3.5
env:
- pipenv
install:
- pipenv install
script:
- py.test --cov=tests
branches:
  only:
  - sivubranch
  - master
deploy:
  provider: heroku
  api_key:
    secure: TMyWNzO7d9qlWptirAsh3nhCCepObkGDxeaHJU+cyrQx9iMe/eYmcxgYxN/QzfahtLYoKfUeIZfhPioOpwha10rc71KG6vYDkh+bqYVuuZ/uJA1c9zpRjWhldnp/Lxv2tbTvEZnaaO2kz069HfyWLrp6hIyZuTEvaOEipFYJqJDzofpJdL52ON3Wsl3McQK9+ZdPcwUkjzwg9V0APWJcyaih8ZCqikZpugRDn/QQZyJArRcnyYPUnYeNMA/fyJ0E8YX9jruB3HeY9Rt6Lv0n7E5YnC0f3p4fhBvTvaUXtkOJZZDu4pHAybTPWZ//w8PlooW2mLGiQ+rCN+Pcig4urEAOchdlC9r+58wci1W1K7ZvRmPV904XAVyPZqvgGVEY6o27Y4nXpNnSaNKnRjZMz+FDDTxXdAuGWqetod6zFIoFxuJU9OowinpDv+c/P6aBWGq4mzVjCyP40a3DvTnOnK1rSR4HWK1PDRPVtUTDlz45zXxP6CItY3yIDq0RdN73PsE/w5hdTzMkb08OI/ORU3mUvZ+ghy/YMybQytAG37IOvevA0K+g6dHByQ1E8zCll6BgiNtbpWWihukGGVpJP3RuEZGA04WdjLxUxgRhtC1/SnH/QlGyczGxqDC8C1zdif8A199DhpljABsXshCGOp+uO9XBelwk4NxsGR8mQLU=
  app: flaskappteam
  on:
    repo: sivu-t/flaskappteam
    all_branches: true
