language: python
python:
- 3.5
env:
- pipenv
install:
- pipenv install
script:
- py.test --cov=tests
branches:
  only:
  - sivubranch
  - master
deploy:
  provider: heroku
  api_key:
    secure: jvqJgfthkPBLJFICVlCki4ZFIWaKtI+A6vvm7rsLABH2lTqFaUZgYIl4SNyRg9oQ49JYIMhppTgpixHd9uJcO+qsG/vmc79I/FyCECMSm5yb4MBfrm3pb5Hq+Hr9LnolZF16Uxl2UUk7uNtmVqKWvMsC1exchknkWc/TXnxa9n0hmPa2dv42pFC7CzfMZ6s6Qt6APcKNpPUcFoqNc5FBfwFl0HVwGZhTOu7Bkh4fWeicX2hYjzToxv/4puFeRwmdR7kRCd3Cp5JHXNDUjW7hJHCk2g1/G3UzRLSxYvb9pHGPFie2adOkvVuuMEj9ApKJOVTNpv3YwSlayDbwy/JPXQYsEIA4iHbwhF4gFivxybSzA4p+EXIU5mOJErzej9VnRGRUcyuN0nRJw6CBLYUfUa6QNhmpWcH1L8KEH2QP4/xy4BAj0TamblFdOu6wFfTTCw8QWD1AQ08A5TcBUouKoucA9yRsojk8Pvx2dDXxosQLAGFoh/d9yt8cW0Kj2bSJq5lAcsu+LnwNzmr1RZseLta7wIz6/Gl2RvtHh4qxvM2kLX7RLcpfEt07GoPw7BB5sfopUW5xR7QvejbPxt+GHn30+HVSob+X/mGuWVcqpcPcljPIsnCKTabJrOehZLFjtSoBozcR75VTZBoVYx4x2euTSSpj0QN0HcLYiPhuraE=
  app: flaskappteam
  on:
    repo: sivu-t/flaskappteam
    branch: sivubranch
