language: python
python:
- 3.5
env:
- pipenv
install:
- pipenv install
script:
- py.test --cov=tests
branches:
  only:
  - sivubranch
  - master
deploy:
  provider: heroku
  api_key:
    secure: f7v0RZN7hVJrxVKjY+T5SU0NAMOkZVV327HcWNaj71hyodSzFqDsFkLRXuiDNItHhFhBxFpxfiKMNFoy/bd0vzNK0WPyjaubHeRY4qQR+hr7xy3a2+2Us/7NBz729YiC4iLTswRmdH01U4LPKfySrJsM5iVtjtSppRtpLNNtIsS/ccOxfuwYB1RatIaLA2IMga8IvbsI5hAENn6XRYNV2LzXg+w+k6SYf39Ufk0QfX57psuP2OecKviE67Z5o4XRjvtVuMHtA8nHxkasclQO5eNaumNRpTxQpqaukxMu9kH+pN+elDxdmjvSiQnV40VrB3cJeV0qtHD/S92oZGVPfDGWouXl4fBscTqaukv+YFxtfJRjOtyEhklKYnUGApqbsHHYZud4IaKL7uOOAouhjj7m4LNLZJOrTVtqVZTgkmgjMbQ7AaSTXell5/5FXKYCYBFUcyN0/pUAh+xQkLK10cXqLZk3he2KoIidSovKorcxULNWrrwSbV1r4ydqDXakUc4KqdHKA5ZR3oeesCmxlKTQNel7s06LDYc1wrD1Xf9U8qJojv4geAf2P/i/+9kf5I2x+uCHjWrFHE94PYmMTx8LX4Mbz5D5XssC1FM+LwK8sklherBeH7zlChYYaShWY8vJL1CmLLNTxTDJRd+F1Y5/LWu5FsCKjnNPZQpBc48=
  app: flaskappteam
  on:
    repo: sivu-t/flaskappteam
    all_branches: true
